
package es.udc.ws.events.client.service.soap.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EventsProvider", targetNamespace = "http://soap.ws.udc.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EventsProvider {


    /**
     * 
     * @param eventId
     * @throws SoapInstanceNotFoundException
     * @throws SoapEventRegisterUsersError
     */
    @WebMethod
    @RequestWrapper(localName = "removeEvent", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.RemoveEvent")
    @ResponseWrapper(localName = "removeEventResponse", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.RemoveEventResponse")
    public void removeEvent(
        @WebParam(name = "eventId", targetNamespace = "")
        Long eventId)
        throws SoapEventRegisterUsersError, SoapInstanceNotFoundException
    ;

    /**
     * 
     * @param eventId
     * @return
     *     returns es.udc.ws.events.client.service.soap.wsdl.EventDto
     * @throws SoapInstanceNotFoundException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEvent", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.FindEvent")
    @ResponseWrapper(localName = "findEventResponse", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.FindEventResponse")
    public EventDto findEvent(
        @WebParam(name = "eventId", targetNamespace = "")
        Long eventId)
        throws SoapInstanceNotFoundException
    ;

    /**
     * 
     * @param eventDto
     * @return
     *     returns java.lang.Long
     * @throws SoapInputValidationException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEvent", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.AddEvent")
    @ResponseWrapper(localName = "addEventResponse", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.AddEventResponse")
    public Long addEvent(
        @WebParam(name = "eventDto", targetNamespace = "")
        EventDto eventDto)
        throws SoapInputValidationException
    ;

    /**
     * 
     * @param username
     * @param eventId
     * @param code
     * @return
     *     returns java.lang.Long
     * @throws SoapOverCapacityError
     * @throws SoapInstanceNotFoundException
     * @throws SoapEventRegisterUsersError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "responseToEvent", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.ResponseToEvent")
    @ResponseWrapper(localName = "responseToEventResponse", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.ResponseToEventResponse")
    public Long responseToEvent(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "eventId", targetNamespace = "")
        Long eventId,
        @WebParam(name = "code", targetNamespace = "")
        Boolean code)
        throws SoapEventRegisterUsersError, SoapInstanceNotFoundException, SoapOverCapacityError
    ;

    /**
     * 
     * @param eventId
     * @param code
     * @return
     *     returns java.util.List<es.udc.ws.events.client.service.soap.wsdl.ResponseDto>
     * @throws SoapInstanceNotFoundException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResponses", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.GetResponses")
    @ResponseWrapper(localName = "getResponsesResponse", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.GetResponsesResponse")
    public List<ResponseDto> getResponses(
        @WebParam(name = "eventId", targetNamespace = "")
        Long eventId,
        @WebParam(name = "code", targetNamespace = "")
        Boolean code)
        throws SoapInstanceNotFoundException
    ;

    /**
     * 
     * @param responseId
     * @return
     *     returns es.udc.ws.events.client.service.soap.wsdl.ResponseDto
     * @throws SoapInstanceNotFoundException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResponsesByID", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.GetResponsesByID")
    @ResponseWrapper(localName = "getResponsesByIDResponse", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.GetResponsesByIDResponse")
    public ResponseDto getResponsesByID(
        @WebParam(name = "responseId", targetNamespace = "")
        Long responseId)
        throws SoapInstanceNotFoundException
    ;

    /**
     * 
     * @param eventDto
     * @throws SoapInstanceNotFoundException
     * @throws SoapEventRegisterUsersError
     * @throws SoapInputValidationException
     */
    @WebMethod
    @RequestWrapper(localName = "updateEvent", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.UpdateEvent")
    @ResponseWrapper(localName = "updateEventResponse", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.UpdateEventResponse")
    public void updateEvent(
        @WebParam(name = "eventDto", targetNamespace = "")
        EventDto eventDto)
        throws SoapEventRegisterUsersError, SoapInputValidationException, SoapInstanceNotFoundException
    ;

    /**
     * 
     * @param dateSt
     * @param clave
     * @param duracion
     * @return
     *     returns java.util.List<es.udc.ws.events.client.service.soap.wsdl.EventDto>
     * @throws SoapInstanceNotFoundException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEventByKeyword", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.FindEventByKeyword")
    @ResponseWrapper(localName = "findEventByKeywordResponse", targetNamespace = "http://soap.ws.udc.es/", className = "es.udc.ws.events.client.service.soap.wsdl.FindEventByKeywordResponse")
    public List<EventDto> findEventByKeyword(
        @WebParam(name = "clave", targetNamespace = "")
        String clave,
        @WebParam(name = "dateSt", targetNamespace = "")
        XMLGregorianCalendar dateSt,
        @WebParam(name = "duracion", targetNamespace = "")
        Integer duracion)
        throws SoapInstanceNotFoundException
    ;

}
